# mysql 的数据库配置
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/document?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver

  thymeleaf:
     cache: false
     prefix: classpath:/templates/
     suffix: .html
     encoding: UTF-8
     content-type: text/html
     mode: HTML5

# spring mvc 视图解析器
  #mvc:
   #view:
     #prefix: classpath:/templates/ # 页面默认前缀目录
     #suffix: .html # 响应页面默认后缀

# 加载Mybatis配置文件
mybatis:
  mapper-locations: classpath:mappers/*Mapper.xml
  type-aliases-package: com.zsz.pojo

# 热部署
  devtools:
    restart:
      enabled: true #热部署生效
      #设置重启的目录
      additional-paths: src/main/java
      exclude: src/main/resources/* #classpath目录下的WEB-INF文件夹内容修改不重启